python3 -i train.py \
    --task concode \
    --lang java \
    --data_dir data/concode/dataset/concode \
    --cache_path data/concode \
    --summary_dir checkpoint/summary \
    --res_dir checkpoint/result \
    --output_dir checkpoint/output \
    --model_name_or_path checkpoint/weights/concode_codet5_base.bin \
    --do_test \
    --do_train \
    --do_eval \
    --num_train_epochs 30 \
    --batch_size 8 \
    --learning_rate 1e-4 \
    --beam_size 10 \
    --patience 3 \
    --weight_decay 1e-5 \
    --gradient_accumulation_steps 4 \
    --max_source_length 320 \
    --max_target_length 150 \
    --warmup_steps 1000 \
    --k 0
